### ISSUE TITLE
Some texts does not extract perfectly

### ISSUE THREAD

**Issue by Ali-YousefiTelori** [VerifyTests/Verify.PdfPig#1]
Hi I'll upload a simple pdf file to you and you can extract the words and you will see some bugs here.

extracted text:
"A slightly more complicated solution is necessary is s.Length exceeds Int32.MaxValue. But ifyou need to read a stream that large into memory, you might want to think about a differentapproach to your problem.This is a text example from Ali Yousefi. Everybody knows this is a test example!"

1.differentapproach  => different approach
2.problem.This => problem. This or have a \r\n
3.ifyou  => if you 

I think this is mixed with every line in the pdf.

[Untitled document-4.pdf](https://github.com/VerifyTests/Verify.PdfPig/files/9927296/Untitled.document-4.pdf)

**Comment by SimonCropp** [comment]
can you share a failing unit test as  a PullRequest

**Comment by Ali-YousefiTelori** [comment]
@SimonCropp  I'm using the nuget package version 2.0.0:
https://www.nuget.org/packages/Verify.PdfPig/2.0.0

**Comment by SimonCropp** [comment]
yep. but can you share a failing unit test as a PullRequest

**Comment by Ali-YousefiTelori** [comment]
Ok, I'll do that, but there are some compile errors in the preview version of dot net, trying to fix the compile errors.

**Comment by Ali-YousefiTelori** [comment]
@SimonCropp pull request created with a failed test case #2
